### ISSUE TITLE
wann_train.py error

### ISSUE THREAD

**Issue by sherlockbear** [google/brain-tokyo-workshop#11]
runfile('D:/Desktop/evolution/code/WANN/wann_train.py', wdir='D:/Desktop/evolution/code/WANN')
['mpirun', '-np', '9', 'C:\\Users\\administered\\Anaconda3\\pythonw.exe', 'D:/Desktop/evolution/code/WANN/wann_train.py']
Traceback (most recent call last):

  File "<ipython-input-1-21d4882e3946>", line 1, in <module>
    runfile('D:/Desktop/evolution/code/WANN/wann_train.py', wdir='D:/Desktop/evolution/code/WANN')

  File "C:\Users\administered\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\administered\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Desktop/evolution/code/WANN/wann_train.py", line 283, in <module>
    if "parent" == mpi_fork(args.num_worker+1): os._exit(0)

  File "D:/Desktop/evolution/code/WANN/wann_train.py", line 233, in mpi_fork
    subprocess.check_call(["mpirun", "-np", str(n), sys.executable] +['-u']+ sys.argv, env=env)

  File "C:\Users\administered\Anaconda3\lib\subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)

  File "C:\Users\administered\Anaconda3\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:

  File "C:\Users\administered\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 143, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\administered\Anaconda3\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)

  File "C:\Users\administered\Anaconda3\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by sherlockbear** [comment]
It seems like there is something goes wrong with the mpi4py, but i'm already use the version==3.0. This error happened in win10 system.

**Comment by MANXIU** [comment]
replace File "D:/Desktop/evolution/code/WANN/wann_train.py", line 233, in mpi_fork
subprocess.check_call(["mpirun", "-np", str(n), sys.executable] +['-u']+ sys.argv, env=env)
with File "D:/Desktop/evolution/code/WANN/wann_train.py", line 233, in mpi_fork
subprocess.check_call(["mpiexec", "-n", str(n), sys.executable] +['-u']+ sys.argv, env=env)

**Comment by sherlockbear** [comment]
There's no longer an error! Thanks!

**Comment by sherlockbear** [comment]
> replace File "D:/Desktop/evolution/code/WANN/wann_train.py", line 233, in mpi_fork
> subprocess.check_call(["mpirun", "-np", str(n), sys.executable] +['-u']+ sys.argv, env=env)
> with File "D:/Desktop/evolution/code/WANN/wann_train.py", line 233, in mpi_fork
> subprocess.check_call(["mpiexec", "-n", str(n), sys.executable] +['-u']+ sys.argv, env=env)

There's another problem. Now that the program just stack in line 233 and can not get through.

**Comment by MANXIU** [comment]
not stack ,its just begin to calculate the model,that,s how the code works

**Comment by sherlockbear** [comment]
So I can only wait until it ends? How long should it takes? Is there a progress bar?

**Comment by sherlockbear** [comment]
Oh, I found out where the problem is. I used to use the spyder to run the file directly. When I run the terminal, the program runs normally. Thank you for your help!

**Comment by jli113** [comment]
I have the same error when running on windows, but it works when running on ubuntu.
