### ISSUE TITLE
AttentionAgent: can't run pretrained CarRacing examples because of doom problems?

### ISSUE THREAD

**Issue by maraoz** [google/brain-tokyo-workshop#25]
I installed dependencies like the README says, first running 
```
pip3 install -r requirements.txt
```
then changing `gym[box2d]==0.15.3` to `gym==0.9.4` and re-running `pip3 install -r requirements.txt`, but when I run `pip3 install -r requirements.txt`, I get this error:
```
Traceback (most recent call last):
  File "test_solution.py", line 63, in <module>
    gin.parse_config_file(os.path.join(args.log_dir, 'config.gin'))
  File "/Users/manu/anaconda3/envs/attention/lib/python3.6/site-packages/gin/config.py", line 1436, in parse_config_file
    parse_config(f, skip_unknown=skip_unknown)
  File "/Users/manu/anaconda3/envs/attention/lib/python3.6/site-packages/gin/config.py", line 1373, in parse_config
    __import__(statement.module)
  File "/Users/manu/anaconda3/envs/attention/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/manu/anaconda3/envs/attention/lib/python3.6/site-packages/gin/utils.py", line 68, in try_with_location
    augment_exception_message_and_reraise(exception, _format_location(location))
  File "/Users/manu/anaconda3/envs/attention/lib/python3.6/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/Users/manu/anaconda3/envs/attention/lib/python3.6/site-packages/gin/utils.py", line 66, in try_with_location
    yield
  File "/Users/manu/anaconda3/envs/attention/lib/python3.6/site-packages/gin/config.py", line 1373, in parse_config
    __import__(statement.module)
  File "/Users/manu/git/brain-tokyo-workshop/AttentionAgent/tasks/gym_task.py", line 10, in <module>
    from takecover_variants.doom_take_cover import DoomTakeCoverEnv
  File "/Users/manu/git/brain-tokyo-workshop/AttentionAgent/takecover_variants/doom_take_cover.py", line 2, in <module>
    from .doom_env import DoomEnv
  File "/Users/manu/git/brain-tokyo-workshop/AttentionAgent/takecover_variants/doom_env.py", line 18, in <module>
    "with 'pip install doom_py.)'".format(e))
gym.error.DependencyNotInstalled: {}. (HINT: you can install Doom dependencies with 'pip install doom_py.)'
  In file "pretrained/CarRacing/config.gin", line 4
    import tasks.gym_task
```

which seems Doom related. 
Is there any way I can run the CarRacing example without installing `doom_py`? (I've tried but I couldn't get to installing it). I also don't have `docker` :)

**Comment by maraoz** [comment]
yay! I got it to work by deleting all mentions references to `doom` in `tasks/gym_task.py`

![image](https://user-images.githubusercontent.com/287189/87365317-53108780-c54c-11ea-83b7-98682c845e55.png)

You might want to check your `requirements.txt` though, seems to be lacking some doom-related stuff (if I can getting working I'll submit a PR)

**Comment by lerrytang** [comment]
Hi, thanks for trying out the code.

> I got it to work by deleting all mentions references to doom in tasks/gym_task.py
I thought I isolated the 2 tasks, but apparently not.
I'll look into this, thanks for bringing this up.
