### ISSUE TITLE
python3 neat_train.py error

### ISSUE THREAD

**Issue by robotzheng** [google/brain-tokyo-workshop#4]
[root@A01-R04-I221-48 prettyNEAT]# python3 neat_train.py
['mpirun', '-np', '9', '/usr/bin/python3', 'neat_train.py']
0 	 - 	 |---| Elite Fit: 352.73 	|---| Best Fit:  352.73
Traceback (most recent call last):
  File "neat_train.py", line 279, in <module>
    main(args)                              
  File "neat_train.py", line 253, in main
    master()
  File "neat_train.py", line 29, in master
    pop = neat.ask()            # Get newly evolved individuals from NEAT  
  File "/home/zzt/brain-tokyo-workshop/WANNRelease/prettyNEAT/neat_src/neat.py", line 51, in ask
    self.evolvePop()    # Create child population 
  File "/home/zzt/brain-tokyo-workshop/WANNRelease/prettyNEAT/neat_src/_variation.py", line 14, in evolvePop
    self.innov, self.gen)
  File "/home/zzt/brain-tokyo-workshop/WANNRelease/prettyNEAT/neat_src/_variation.py", line 81, in recombine
    mate=pop[parents[1,i]])
  File "/home/zzt/brain-tokyo-workshop/WANNRelease/prettyNEAT/neat_src/ind.py", line 98, in createChild
    child = self.crossover(mate)
  File "/home/zzt/brain-tokyo-workshop/WANNRelease/prettyNEAT/neat_src/ind.py", line 139, in crossover
    matching, IA, IB = np.intersect1d(aConn,bConn,return_indices=True)
TypeError: intersect1d() got an unexpected keyword argument 'return_indices'

**Comment by agaier** [comment]
Hi!

Try upgrading your numpy version, the keyword argument 'return_indices' is new in 1.15.0

from: [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.intersect1d.html)
